[package]
name = "mrky"
version = "0.1.0"
edition = "2021"

[dependencies]
compio = {version = "0.13.2", features = ["runtime", "io", "bytes"]}
redis-protocol = {version = "6.0.0", features = ["default", "bytes"]}
anyhow = "1.0.95"
crossbeam-channel = "0.5.14"
crc32fast = "1.4.2"